name: Deploying Lambda Function
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      # create_movie
      - run: zip -j create_movie.zip ./create_movie/*
      - run: zip -r create_movie.zip ./common
      - run: aws lambda update-function-code --function-name=zps-portfolio-create-movie --zip-file=fileb://create_movie.zip

      # get_movie_list
      - run: zip -j get_movie_list.zip ./get_movie_list/*
      - run: aws lambda update-function-code --function-name=zps-portfolio-get-movie-list --zip-file=fileb://get_movie_list.zip

      # event_projector
      - run: zip -j event_projector.zip ./event_projector/*
      - run: zip -r event_projector.zip ./common
      - run: zip -r event_projector.zip ./projections
      - run: aws lambda update-function-code --function-name=zps-portfolio-event-projector --zip-file=fileb://event_projector.zip
